ALTER TABLE leads ADD COLUMN phone TEXT;
ALTER TABLE leads ADD COLUMN website TEXT;
ALTER TABLE leads ADD COLUMN preferred_contact_method TEXT;
ALTER TABLE leads ADD COLUMN best_time_to_contact TEXT;
ALTER TABLE leads ADD COLUMN social_profiles_json TEXT;
ALTER TABLE leads ADD COLUMN linkedin_url TEXT;
ALTER TABLE leads ADD COLUMN business_phone TEXT;
ALTER TABLE leads ADD COLUMN business_email TEXT;
ALTER TABLE leads ADD COLUMN industry TEXT;
ALTER TABLE leads ADD COLUMN business_type TEXT;
ALTER TABLE leads ADD COLUMN company_size TEXT;
ALTER TABLE leads ADD COLUMN revenue_range TEXT;
ALTER TABLE leads ADD COLUMN location TEXT;
ALTER TABLE leads ADD COLUMN city TEXT;
ALTER TABLE leads ADD COLUMN state_region TEXT;
ALTER TABLE leads ADD COLUMN country TEXT;
ALTER TABLE leads ADD COLUMN timezone TEXT;
ALTER TABLE leads ADD COLUMN business_state TEXT;
ALTER TABLE leads ADD COLUMN need_summary TEXT;
ALTER TABLE leads ADD COLUMN urgency TEXT NOT NULL DEFAULT 'Normal';
ALTER TABLE leads ADD COLUMN urgency_reason TEXT;
ALTER TABLE leads ADD COLUMN priority TEXT NOT NULL DEFAULT 'medium';
ALTER TABLE leads ADD COLUMN estimated_value_cents INTEGER NOT NULL DEFAULT 0;
ALTER TABLE leads ADD COLUMN deal_type TEXT;
ALTER TABLE leads ADD COLUMN stage TEXT NOT NULL DEFAULT 'New';
ALTER TABLE leads ADD COLUMN qr_source TEXT;
ALTER TABLE leads ADD COLUMN referral_source TEXT;
ALTER TABLE leads ADD COLUMN received_at TEXT;
ALTER TABLE leads ADD COLUMN last_contacted_at TEXT;
ALTER TABLE leads ADD COLUMN assigned_at TEXT;
ALTER TABLE leads ADD COLUMN follow_up_due_at TEXT;
ALTER TABLE leads ADD COLUMN follow_up_sequence TEXT;
ALTER TABLE leads ADD COLUMN follow_up_status TEXT NOT NULL DEFAULT 'not_started';
ALTER TABLE leads ADD COLUMN last_follow_up_at TEXT;
ALTER TABLE leads ADD COLUMN next_scheduled_follow_up_at TEXT;
ALTER TABLE leads ADD COLUMN document_links_json TEXT;
ALTER TABLE leads ADD COLUMN tags_json TEXT;
ALTER TABLE leads ADD COLUMN agent_summary TEXT;
ALTER TABLE leads ADD COLUMN agent_next_move TEXT;
ALTER TABLE leads ADD COLUMN activity_history_json TEXT;
ALTER TABLE leads ADD COLUMN archived_at TEXT;

ALTER TABLE contacts ADD COLUMN full_name TEXT;
ALTER TABLE contacts ADD COLUMN website TEXT;
ALTER TABLE contacts ADD COLUMN preferred_contact_method TEXT;
ALTER TABLE contacts ADD COLUMN best_time_to_contact TEXT;
ALTER TABLE contacts ADD COLUMN role_authority TEXT;
ALTER TABLE contacts ADD COLUMN social_profiles_json TEXT;
ALTER TABLE contacts ADD COLUMN linkedin_url TEXT;
ALTER TABLE contacts ADD COLUMN x_url TEXT;
ALTER TABLE contacts ADD COLUMN instagram_url TEXT;
ALTER TABLE contacts ADD COLUMN facebook_url TEXT;
ALTER TABLE contacts ADD COLUMN other_profile_url TEXT;
ALTER TABLE contacts ADD COLUMN business_phone TEXT;
ALTER TABLE contacts ADD COLUMN business_email TEXT;
ALTER TABLE contacts ADD COLUMN industry TEXT;
ALTER TABLE contacts ADD COLUMN business_type TEXT;
ALTER TABLE contacts ADD COLUMN company_size TEXT;
ALTER TABLE contacts ADD COLUMN revenue_range TEXT;
ALTER TABLE contacts ADD COLUMN location TEXT;
ALTER TABLE contacts ADD COLUMN city TEXT;
ALTER TABLE contacts ADD COLUMN state_region TEXT;
ALTER TABLE contacts ADD COLUMN country TEXT;
ALTER TABLE contacts ADD COLUMN timezone TEXT;
ALTER TABLE contacts ADD COLUMN business_state TEXT;
ALTER TABLE contacts ADD COLUMN need_summary TEXT;
ALTER TABLE contacts ADD COLUMN urgency TEXT;
ALTER TABLE contacts ADD COLUMN priority TEXT;
ALTER TABLE contacts ADD COLUMN source TEXT;
ALTER TABLE contacts ADD COLUMN qr_source TEXT;
ALTER TABLE contacts ADD COLUMN referral_source TEXT;
ALTER TABLE contacts ADD COLUMN owner_user_id TEXT;
ALTER TABLE contacts ADD COLUMN stage TEXT;
ALTER TABLE contacts ADD COLUMN received_at TEXT;
ALTER TABLE contacts ADD COLUMN last_contacted_at TEXT;
ALTER TABLE contacts ADD COLUMN follow_up_due_at TEXT;
ALTER TABLE contacts ADD COLUMN next_scheduled_follow_up_at TEXT;
ALTER TABLE contacts ADD COLUMN follow_up_sequence TEXT;
ALTER TABLE contacts ADD COLUMN follow_up_status TEXT;
ALTER TABLE contacts ADD COLUMN document_links_json TEXT;
ALTER TABLE contacts ADD COLUMN agent_summary TEXT;
ALTER TABLE contacts ADD COLUMN agent_next_move TEXT;
ALTER TABLE contacts ADD COLUMN activity_history_json TEXT;
ALTER TABLE contacts ADD COLUMN archived_at TEXT;

CREATE INDEX IF NOT EXISTS idx_leads_org_received ON leads (organization_id, received_at);
CREATE INDEX IF NOT EXISTS idx_leads_org_followup ON leads (organization_id, follow_up_due_at);
CREATE INDEX IF NOT EXISTS idx_leads_org_urgency ON leads (organization_id, urgency);
CREATE INDEX IF NOT EXISTS idx_leads_org_source ON leads (organization_id, source);
CREATE INDEX IF NOT EXISTS idx_contacts_org_email ON contacts (organization_id, email);
